version: "3.9"
services:
  laravel.fpm:
    build:
      context: .
      target: fpm_server
    image: forces_gym/fpm_server
    environment:
      APP_DEBUG: "true"
    networks:
      - forces_gym
  laravel.web:
    build:
      context: .
      target: web_server
    image: forces_gym/web_server
    ports:
      - "8080:80"
    environment:
      APP_NAME: "forces_gym"
      FPM_HOST: "laravel.fpm:9000"
    networks:
      - forces_gym
  laravel.frontend:
    build:
      context: .
      target: frontend
    image: forces_gym/frontend
    networks:
      - forces_gym
networks:
  forces_gym:
    driver: bridge
