version: "3.9"
services:
  laravel.fpm:
    build:
      context: .
      target: fpm
    image: forces_gym/fpm
    environment:
      APP_DEBUG: "true"
    networks:
      - forces_gym
  laravel.web:
    build:
      context: .
      target: web
    image: forces_gym/web
    ports:
      - "8080:80"
    environment:
      APP_NAME: "forces_gym"
      FPM_HOST: "laravel.fpm:9000"
    networks:
      - forces_gym
networks:
  forces_gym:
    driver: bridge
