version: "3.9"
services:
  laravel.fpm:
    build:
      context: .
      target: fpm
    image: forcesgym/fpm
    environment:
      APP_DEBUG: "true"
      DB_CONNECTION: <DB_CONNECTION>
      DB_HOST: <DB_HOST>
      DB_PORT: <DB_PORT>
      DB_DATABASE: <DB_DATABASE>
      DB_USERNAME: <DB_USERNAME>
      DB_PASSWORD: <DB_PASSWORD>
    networks:
      - forcesgym
  laravel.web:
    build:
      context: .
      target: web
    image: forcesgym/web
    ports:
      - "8080:80"
    environment:
      APP_NAME: "forcesgym"
      FPM_HOST: "laravel.fpm:9000"
    networks:
      - forcesgym
networks:
  forcesgym:
    driver: bridge
