apiVersion: apps/v1
kind: Deployment
metadata:
  name: forcesgym
  namespace: default
  labels:
    app: forcesgym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forcesgym
  template:
    metadata:
      labels:
        app: forcesgym
    spec:
      containers:
      - name: forcesgym-fpm
        image: 5george/forcesgym:fpm-latest
        ports:
        - containerPort: 9000
        envFrom:
          - configMapRef:
              name: environment
          - secretRef:
              name: secrets
      - name: forcesgym-web
        image: 5george/forcesgym:web-latest
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: environment
