namespace: staging
namePrefix: staging-
resources:
- ../../base
configMapGenerator:
- name: environment
  envs:
    - staging.env
secretGenerator:
- name: secrets
  envs:
  - staging.secrets.env
patches:
 - path: ingress-patch.yaml 
   target:
      kind: Ingress