name: Build Docker image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Multi stage build and push

      - name: Build and push FPM server image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          cache-from: |
            type=gha,scope=fpm
          cache-to: |
            type=gha,mode=max,scope=fpm
          target: fpm
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/forcesgym:fpm-latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          cache-from: |
            type=gha,scope=frontend
            type=gha,scope=fpm
          cache-to: |
            type=gha,mode=max,scope=frontend
          target: frontend
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/forcesgym:frontend-latest

      - name: Build and push Web server image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          cache-from: |
            type=gha,scope=frontend
            type=gha,scope=fpm
            type=gha,scope=web
          cache-to: |
            type=gha,mode=max,scope=web
          target: web
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/forcesgym:web-latest
